"""add warehouse table

Revision ID: c331495e1d0a
Revises: 283fe87ebb5c
Create Date: 2025-11-22 07:00:37.894779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c331495e1d0a'
down_revision: Union[str, Sequence[str], None] = '283fe87ebb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.create_index(op.f('ix_warehouses_short_code'), 'warehouses', ['short_code'], unique=True)
    op.add_column('locations', sa.Column('short_code', sa.String(), nullable=False))
    op.add_column('locations', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_locations_short_code'), 'locations', ['short_code'], unique=False)
    op.drop_constraint(op.f('locations_parent_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_column('locations', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_parent_id_fkey'), 'locations', 'locations', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_locations_short_code'), table_name='locations')
    op.drop_column('locations', 'warehouse_id')
    op.drop_column('locations', 'short_code')
    op.drop_index(op.f('ix_warehouses_short_code'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
